#!/usr/bin/bash
set -x

export MACH_USE_SYSTEM_PYTHON=1

# Fix for system nss
ln -s /usr/bin/certutil objdir/dist/bin/certutil
ln -s /usr/bin/pk12util objdir/dist/bin/pk12util

mkdir test_results
./jsapi-tests >& test_results/check-jsapi || true &
xvfb-run ./mach cppunittest >& test_results/check-cppunittest || true &
xvfb-run ./mach gtest >& test_results/check-gtest || true &
./mach jstests >& test_results/check-jstests || true &
xvfb-run ./mach rusttests >& test_results/check-rusttests || true &
xvfb-run ./mach xpcshell-test >& test_results/check-xpcshell-test || true &

# We can't parallelize these tests
xvfb-run ./mach jstestbrowser >& test_results/check-jstestbrowser || true
xvfb-run ./mach crashtest >& test_results/check-crashtest || true
xvfb-run ./mach marionette-test >& test_results/check-marionette-test || true
xvfb-run ./mach reftest >& test_results/check-reftest || true
xvfb-run ./mach mochitest >& test_results/check-mochitest || true

rm -f  objdir/dist/bin/certutil
rm -f  objdir/dist/bin/pk12util

