#!/usr/bin/bash
set -x

export MACH_USE_SYSTEM_PYTHON=1
export MOZ_NODE_PATH=/usr/bin/node
export TEST_PARAMS=""
export X_PARAMS='-s "-screen 0 1600x1200x24"'

# Fix for system nss
ln -s /usr/bin/certutil objdir/dist/bin/certutil
ln -s /usr/bin/pk12util objdir/dist/bin/pk12util

mkdir test_results

# Basic render testing
xvfb-run "$X_PARAMS" ./mach mochitest $TEST_PARAMS >& test_results/check-mochitest
./mach xpcshell-test $TEST_PARAMS 2>&1 | cat - > test_results/check-xpcshell-test
xvfb-run "$X_PARAMS" ./mach jstestbrowser $TEST_PARAMS >& test_results/check-jstestbrowser
xvfb-run "$X_PARAMS" ./mach crashtest $TEST_PARAMS --run-tests-in-parallel >& test_results/check-crashtest
xvfb-run "$X_PARAMS" ./mach marionette-test $TEST_PARAMS >& test_results/check-marionette-test
xvfb-run "$X_PARAMS" ./mach reftest $TEST_PARAMS --run-tests-in-parallel >& test_results/check-reftest

# WebRender testing
TEST_PARAMS="--enable-webrender $TEST_PARAMS"
xvfb-run "$X_PARAMS" ./mach mochitest $TEST_PARAMS >& test_results/check-mochitest-wr
./mach xpcshell-test $TEST_PARAMS 2>&1 | cat - > test_results/check-xpcshell-test-wr
xvfb-run "$X_PARAMS" ./mach jstestbrowser $TEST_PARAMS >& test_results/check-jstestbrowser-wr
xvfb-run "$X_PARAMS" ./mach crashtest $TEST_PARAMS --run-tests-in-parallel >& test_results/check-crashtest-wr
xvfb-run "$X_PARAMS" ./mach marionette-test $TEST_PARAMS >& test_results/check-marionette-test-wr
xvfb-run "$X_PARAMS" ./mach reftest $TEST_PARAMS --run-tests-in-parallel >& test_results/check-reftest-wr

# Rest
objdir/dist/bin/jsapi-tests >& test_results/check-jsapi
./mach cppunittest >& test_results/check-cppunittest
./mach gtest >& test_results/check-gtest
./mach rusttests >& test_results/check-rusttests
./mach jstests >& test_results/check-jstests

rm -f  objdir/dist/bin/certutil
rm -f  objdir/dist/bin/pk12util
